# Generated by Django 2.2.5 on 2019-10-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tally',
            name='total_tally',
            field=models.IntegerField(default=0),
        ),
    ]
